import type { Command } from '@/types'

export const commandRegistry: Command[] = [
  {
    id: 'git-status',
    name: 'Git Status',
    description: 'Show the working tree status',
    category: 'github',
    command: 'git status',
    shortcut: 'gs',
    icon: 'GitBranch',
    status: 'wired',
  },
  {
    id: 'git-pull',
    name: 'Git Pull',
    description: 'Fetch and merge changes from remote',
    category: 'github',
    command: 'git pull origin $(git branch --show-current)',
    shortcut: 'gpl',
    icon: 'GitBranch',
    status: 'wired',
  },
  {
    id: 'git-push',
    name: 'Git Push',
    description: 'Push commits to remote repository',
    category: 'github',
    command: 'git push origin $(git branch --show-current)',
    shortcut: 'gps',
    icon: 'GitBranch',
    status: 'stub',
  },
  {
    id: 'git-branch',
    name: 'Create Branch',
    description: 'Create and checkout a new branch',
    category: 'github',
    command: 'git checkout -b',
    icon: 'GitBranch',
    status: 'stub',
    params: [{ name: 'branch-name', type: 'string', required: true }],
  },
  {
    id: 'git-commit',
    name: 'Git Commit',
    description: 'Commit staged changes with a message',
    category: 'github',
    command: 'git commit -am',
    icon: 'GitBranch',
    status: 'stub',
  },
  {
    id: 'git-sync-rebase',
    name: 'Sync Repo',
    description: 'Fetch and rebase with remote main',
    category: 'github',
    command: 'git pull --rebase',
    icon: 'GitBranch',
    status: 'wired',
  },
  {
    id: 'vercel-preview',
    name: 'Deploy Preview',
    description: 'Deploy a preview version',
    category: 'vercel',
    command: 'vercel',
    shortcut: 'vp',
    icon: 'Cloud',
    status: 'wired',
  },
  {
    id: 'vercel-prod',
    name: 'Deploy Production',
    description: 'Deploy to production environment',
    category: 'vercel',
    command: 'vercel --prod',
    shortcut: 'vprod',
    icon: 'Cloud',
    status: 'wired',
    requiresConfirmation: true,
  },
  {
    id: 'vercel-list',
    name: 'List Deployments',
    description: 'Show recent deployments',
    category: 'vercel',
    command: 'vercel list',
    icon: 'Cloud',
    status: 'wired',
  },
  {
    id: 'docker-up',
    name: 'Docker Compose Up',
    description: 'Start all containers in detached mode',
    category: 'docker',
    command: 'docker-compose up -d',
    shortcut: 'dcu',
    icon: 'Container',
    status: 'wired',
  },
  {
    id: 'docker-down',
    name: 'Docker Compose Down',
    description: 'Stop and remove containers',
    category: 'docker',
    command: 'docker-compose down',
    shortcut: 'dcd',
    icon: 'Container',
    status: 'wired',
    dangerous: true,
  },
  {
    id: 'docker-build',
    name: 'Docker Build',
    description: 'Build Docker image from Dockerfile',
    category: 'docker',
    command: 'docker build -t',
    icon: 'Container',
    status: 'stub',
    params: [{ name: 'image-name', type: 'string', required: true }],
  },
  {
    id: 'db-studio',
    name: 'Prisma Studio',
    description: 'Open Prisma Studio GUI',
    category: 'database',
    command: 'npx prisma studio',
    shortcut: 'pst',
    icon: 'Database',
    status: 'wired',
  },
  {
    id: 'db-migrate',
    name: 'Run Migrations',
    description: 'Apply pending database migrations',
    category: 'database',
    command: 'npx prisma migrate dev',
    icon: 'Database',
    status: 'wired',
  },
  {
    id: 'db-generate',
    name: 'Generate Client',
    description: 'Generate Prisma client',
    category: 'database',
    command: 'npx prisma generate',
    icon: 'Database',
    status: 'wired',
  },
  {
    id: 'npm-install',
    name: 'Install Dependencies',
    description: 'Install all project dependencies',
    category: 'npm',
    command: 'npm install',
    shortcut: 'ni',
    icon: 'Package',
    status: 'wired',
  },
  {
    id: 'npm-dev',
    name: 'Dev Server',
    description: 'Start development server',
    category: 'npm',
    command: 'npm run dev',
    shortcut: 'nd',
    icon: 'Package',
  },
  {
    id: 'npm-build',
    name: 'Build',
    description: 'Build for production',
    category: 'npm',
    command: 'npm run build',
    shortcut: 'nb',
    icon: 'Package',
    status: 'wired',
  },
  {
    id: 'ssh-connect',
    name: 'Connect to Server',
    description: 'SSH into remote server',
    category: 'ssh',
    command: 'ssh',
    icon: 'Server',
    status: 'stub',
    params: [{ name: 'user@host', type: 'string', required: true }],
  },
  {
    id: 'wf-full-deploy',
    name: 'Full Deploy',
    description: 'Run tests, build, and deploy to production',
    category: 'workflow',
    command: 'npm test && npm run build && vercel --prod',
    icon: 'Workflow',
    status: 'wired',
    requiresConfirmation: true,
  },
  {
    id: 'wf-fresh-start',
    name: 'Fresh Start',
    description: 'Clean install and restart dev server',
    category: 'workflow',
    command: 'rm -rf node_modules && npm install && npm run dev',
    icon: 'Workflow',
    status: 'wired',
  },
  {
    id: 'wf-sync-install',
    name: 'Sync + Install',
    description: 'Pull latest changes and install dependencies',
    category: 'workflow',
    command: 'git pull && npm install',
    icon: 'Workflow',
    status: 'wired',
  },
  {
    id: 'terminal-open',
    name: 'Open Terminal',
    description: 'Open a local terminal window',
    category: 'custom',
    command: 'open-terminal',
    icon: 'Terminal',
    status: 'stub',
  },
  {
    id: 'project-new',
    name: 'New Project',
    description: 'Create a new project workspace',
    category: 'custom',
    command: 'create-project',
    icon: 'Workflow',
    status: 'stub',
  },
]

export const baseCommands = commandRegistry

export function findCommand(query: string) {
  return commandRegistry.filter((command) =>
    command.name.toLowerCase().includes(query.toLowerCase())
  )
}

export function getCommandById(id: string) {
  return commandRegistry.find((command) => command.id === id)
}
